# Generated by Django 3.2 on 2022-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccess',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('executive', 'executive')], default='admin', max_length=25),
        ),
    ]
